server:
  servlet:
    context-path: /${spring.application.name}

  port: 8080

spring:
  application:
    name: Spring_AngularDemo
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres
    username: postgres.clnozydxexsdfvycqzjr
    password: springdatabase_demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
